### ISSUE TITLE
Check out Atom

### ISSUE THREAD

**Issue by jayswan** [gjhinson/ciscogeek#3]
Replace Notepad++ with [Atom](https://atom.io/).

There's nothing terribly wrong with Notepad++ (I assume that's what you're using), but Atom is a lot more modern and works exactly the same on Mac, Linux, and Windows. It's also super extensible. My colleague Scott has an intro here:

http://sroberts.github.io/2015/06/06/how-i-atom/

**Comment by gjhinson** [comment]
i'll check out his intro, thanks for the tip!
